import type { SectionTemplateDefinition } from './templateTypes'
import { checkboxRow, featureRow, rootContainer } from './templateBlocks'

export const SECTION_TEMPLATE_DEFINITIONS: SectionTemplateDefinition[] = [
  {
    id: 'mobile-hero-cta',
    name: 'Hero CTA',
    description: 'Headline, supporting text, and primary action.',
    category: 'section',
    preview: 'Intro',
    bounds: { cols: 14, rows: 9 },
    blocks: [
      rootContainer('container', 14, 9, '#eff6ff', '#bfdbfe', 22),
      {
        key: 'headline',
        parentKey: 'container',
        type: 'hero',
        grid: { colStart: 2, rowStart: 2, colSpan: 10, rowSpan: 3 },
        props: { headline: 'Launch faster', headlineSize: 26 },
        render: { alignX: 'start', alignY: 'start' },
      },
      {
        key: 'body',
        parentKey: 'container',
        type: 'text',
        grid: { colStart: 2, rowStart: 5, colSpan: 11, rowSpan: 2 },
        props: { value: 'Build a polished mobile screen from simple blocks.', fontSize: 15 },
        render: { alignX: 'start', alignY: 'start' },
      },
      {
        key: 'primaryAction',
        parentKey: 'container',
        type: 'navButton',
        grid: { colStart: 2, rowStart: 7, colSpan: 6, rowSpan: 2 },
        props: { label: 'Get Started', backgroundColor: '#2563eb', borderRadius: 12 },
        render: { alignX: 'start', alignY: 'start' },
      },
    ],
  },
  {
    id: 'signup-form',
    name: 'Signup Form',
    description: 'Mock form layout with fields and submit action.',
    category: 'section',
    preview: 'Form',
    bounds: { cols: 14, rows: 14 },
    blocks: [
      rootContainer('container', 14, 14, '#ffffff', '#dbeafe', 20),
      {
        key: 'title',
        parentKey: 'container',
        type: 'text',
        grid: { colStart: 2, rowStart: 2, colSpan: 10, rowSpan: 2 },
        props: { value: 'Create your account', fontSize: 20 },
        render: { alignX: 'start', alignY: 'start' },
      },
      {
        key: 'email',
        parentKey: 'container',
        type: 'input',
        grid: { colStart: 2, rowStart: 5, colSpan: 11, rowSpan: 3 },
        props: { label: 'Email', placeholder: 'you@example.com', inputType: 'email' },
      },
      {
        key: 'notes',
        parentKey: 'container',
        type: 'textarea',
        grid: { colStart: 2, rowStart: 8, colSpan: 11, rowSpan: 4 },
        props: { label: 'Notes', placeholder: 'Tell us what you need' },
      },
      {
        key: 'submit',
        parentKey: 'container',
        type: 'navButton',
        grid: { colStart: 2, rowStart: 12, colSpan: 6, rowSpan: 2 },
        props: { label: 'Submit', backgroundColor: '#2563eb', borderRadius: 12 },
        render: { alignX: 'start', alignY: 'start' },
      },
    ],
  },
  {
    id: 'feature-list',
    name: 'Feature List',
    description: 'Three simple feature rows with icons and text.',
    category: 'section',
    preview: 'Features',
    bounds: { cols: 14, rows: 10 },
    blocks: [
      rootContainer('container', 14, 10, '#ffffff', '#dbeafe', 20),
      ...featureRow('featureOne', 2, 'star', 'Fast setup', 'Start from reusable blocks.'),
      ...featureRow('featureTwo', 5, 'check', 'Native preview', 'Render the same schema on Android.'),
      ...featureRow('featureThree', 8, 'heart', 'Own the app', 'Export and evolve toward real code.'),
    ],
  },
  {
    id: 'checklist-card',
    name: 'Checklist Card',
    description: 'Simple checklist block for tasks or inspections.',
    category: 'section',
    preview: 'Checklist',
    bounds: { cols: 14, rows: 10 },
    blocks: [
      rootContainer('container', 14, 10, '#ffffff', '#e2e8f0', 20),
      {
        key: 'title',
        parentKey: 'container',
        type: 'text',
        grid: { colStart: 2, rowStart: 2, colSpan: 10, rowSpan: 2 },
        props: { value: 'Today\'s checklist', fontSize: 19 },
        render: { alignX: 'start', alignY: 'start' },
      },
      checkboxRow('itemOne', 4, 'Confirm details', true),
      checkboxRow('itemTwo', 6, 'Upload photo', false),
      checkboxRow('itemThree', 8, 'Mark complete', false),
    ],
  },
  {
    id: 'contact-card',
    name: 'Contact Card',
    description: 'Compact contact prompt with message field.',
    category: 'section',
    preview: 'Contact',
    bounds: { cols: 14, rows: 11 },
    blocks: [
      rootContainer('container', 14, 11, '#ffffff', '#dbeafe', 22),
      {
        key: 'title',
        parentKey: 'container',
        type: 'text',
        grid: { colStart: 2, rowStart: 2, colSpan: 10, rowSpan: 2 },
        props: { value: 'Send a message', fontSize: 20 },
        render: { alignX: 'start', alignY: 'start' },
      },
      {
        key: 'message',
        parentKey: 'container',
        type: 'textarea',
        grid: { colStart: 2, rowStart: 5, colSpan: 11, rowSpan: 4 },
        props: { label: 'Message', placeholder: 'How can we help?' },
      },
      {
        key: 'send',
        parentKey: 'container',
        type: 'navButton',
        grid: { colStart: 2, rowStart: 9, colSpan: 5, rowSpan: 2 },
        props: { label: 'Send', backgroundColor: '#2563eb' },
        render: { alignX: 'start', alignY: 'start' },
      },
    ],
  },
]
